package com.example.devicemanagement.decision

internal enum class DecisionReason {
    APPROVED_BY_POLICY,
    INVALID_TRIGGER,
    MISSING_STATE,
    SERVICE_UNAVAILABLE,
    INCONSISTENT_MANAGEMENT_STATE,
    PROFILE_OWNER_NOT_ALLOWED,
    ADMIN_RECEIVER_NOT_REGISTERED,
    ADMIN_NOT_ACTIVE,
    DEVICE_OWNER_NOT_VERIFIED,
    SENSITIVE_ACTIONS_DISABLED,
    EVALUATION_ERROR,
}
